-- MySQL Script generated by MySQL Workbench
-- Wed Aug 16 18:16:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema akode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema akode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `akode` DEFAULT CHARACTER SET utf8mb4 ;
USE `akode` ;

-- -----------------------------------------------------
-- Table `akode`.`knowledge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akode`.`knowledge` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akode`.`knowledge_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akode`.`knowledge_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `knowledge_id` INT UNSIGNED NOT NULL,
  `message` MEDIUMTEXT NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_knowledge_comment_knowledge_id_idx` (`knowledge_id` ASC),
  CONSTRAINT `fk_knowledge_comment_knowledge_id`
    FOREIGN KEY (`knowledge_id`)
    REFERENCES `akode`.`knowledge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `akode`.`knowledge` (`id`, `title`, `description`, `create_at`, `update_at`) VALUES ('1', 'testTitle1', 'テステス！！！！！！！', '2017/08/17', '2017/08/17');
INSERT INTO `akode`.`knowledge` (`id`, `title`, `description`, `create_at`, `update_at`) VALUES ('2', 'testTitle2', 'テステス！！！！', '2017/08/17', '2017/08/17');
INSERT INTO `akode`.`knowledge` (`id`, `title`, `description`, `create_at`, `update_at`) VALUES ('3', 'testTitle3', 'テステス！！！', '2017/08/17', '2017/08/17');
